// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbxocDX0wuxh35uEDmZeWoLAvjZw08sN4',
    appId: '1:822768380912:web:e9dc83ca664b1bd71c8b35',
    messagingSenderId: '822768380912',
    projectId: 'ahad-af39b',
    authDomain: 'ahad-af39b.firebaseapp.com',
    storageBucket: 'ahad-af39b.appspot.com',
    measurementId: 'G-C75T04744D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQRqc2wBTe0NrLweEbkp8U3sCITl-jgxs',
    appId: '1:822768380912:android:ac2c59cfc07b471a1c8b35',
    messagingSenderId: '822768380912',
    projectId: 'ahad-af39b',
    storageBucket: 'ahad-af39b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvcsVIFp9jxa617JLRRUqazoF1JKewzLo',
    appId: '1:822768380912:ios:f10126dae83c038e1c8b35',
    messagingSenderId: '822768380912',
    projectId: 'ahad-af39b',
    storageBucket: 'ahad-af39b.appspot.com',
    iosBundleId: 'com.example.ahad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvcsVIFp9jxa617JLRRUqazoF1JKewzLo',
    appId: '1:822768380912:ios:0eeb94bc8264bfc21c8b35',
    messagingSenderId: '822768380912',
    projectId: 'ahad-af39b',
    storageBucket: 'ahad-af39b.appspot.com',
    iosBundleId: 'com.example.ahad.RunnerTests',
  );
}
